FROM node:dubnium

WORKDIR ./

COPY package*.json ./
COPY ./src /src
COPY .babelrc ./
COPY .eslintrc ./
COPY webpack.common.js ./
COPY webpack.prod.js ./
COPY server.js ./

RUN npm install
RUN npm run build

EXPOSE 8080
CMD npm run startProd
